### ISSUE TITLE
.debug param

### ISSUE THREAD

**Issue by popomore** [popomore/coffee#23]
```js
coffee.fork()
.debug(number)
.end();
```

number

- 0 (default): pipe stdout + stderr
- 1: pipe stdout
- 2: pipe stderr

**Comment by hotoo** [comment]
Suggest:

```js
coffee.fork()
.debug(mode)
.end();
```

mode:

* 0: off
* 1: pipe stderr
* 2: (default) pipe stdout + stderr

**Comment by popomore** [comment]
Why?
闲耘™ <notifications@github.com>于2016年1月4日 周一上午9:36写道：
