### ISSUE TITLE
能否多增加几个断言？

### ISSUE THREAD

**Issue by hstarorg** [popomore/coffee#47]
仅仅靠expert和notExpert可能不够使用，另外，控制台输出很有可能是一大串，而且包含换行符之类，很难绝对相对，能否考虑把value传递到外部函数，然后接受外部函数的判断结果？

**Comment by hstarorg** [comment]
发现expect的第二个参数可以输入正则，能否基本上满足这个需求，但是还是不够灵活。输出太复杂，正则并不太好写。

**Comment by popomore** [comment]
expect 支持正则的

```
.expect('stdout', /xxx\n/)
```

可以在 end 做

```
.end(err => {
  should.not.exists(err);
  // assert this.stdout
  // assert this.stderr
})
```

**Comment by hstarorg** [comment]
感谢您的指导，当前采用了expect+正则的方式，后续考虑后者。

BTW：如果命令行工具会操作服务端（比如写数据，提交文件），此时我应该如何在做相关的测试呢？

在此谢过！

**Comment by popomore** [comment]
你是说如果 mock 请求么

**Comment by hstarorg** [comment]
@popomore 类似这样，但不局限与这样。还有一种场景是命令行程序会输出文件。这些感觉都不太好测试！

**Comment by popomore** [comment]
输出文件直接在 end 里去读文件就好了，输出一般都好处理的。

hstar <notifications@github.com>于2016年6月18日 周六上午11:31写道：

**Comment by hstarorg** [comment]
@popomore ，如果目录需要满足特定的条件，那我们还得在运行测试时去构造相关目录，测试完成后去清理目录，是吧。

我描述我命令行工具的作用：从web上请求一个文件，下载到系统临时目录，解压到当前执行命令的目录。

**Comment by popomore** [comment]
是啊，就是断言文件是否存在。
hstar <notifications@github.com>于2016年6月18日 周六下午3:41写道：

**Comment by hstarorg** [comment]
@popomore 感谢指导！
