### ISSUE TITLE
Timeout Error in nodejs@0.12 and iojs@2.0.3

### ISSUE THREAD

**Issue by afc163** [popomore/coffee#6]
https://travis-ci.org/afc163/fanyi/jobs/62964993

```
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Comment by popomore** [comment]
Is the timeout too short for this case?

**Comment by afc163** [comment]
Fixed by https://github.com/afc163/fanyi/commit/6019b35b1efb98274a5da11f258036326369c9bf
