### ISSUE TITLE
自动识别当前仓库的 bin 文件

### ISSUE THREAD

**Issue by afc163** [popomore/coffee#7]
类似 npm.scripts 自动识别 `./node_modules/.bin` 目录下的 bin 。

这样不需要这样全局安装就可以测试。

https://github.com/afc163/fanyi/blob/6019b35b1efb98274a5da11f258036326369c9bf/.travis.yml#L10

**Comment by popomore** [comment]
不需要全局安装呀

```
coffee.fork(path.join(__dirname, '../bin/fanyi'))
```

**Comment by afc163** [comment]
```js
    coffee.fork(path.join(__dirname, '../bin/fanyi'), ['word'])
      .expect('stdout', '123')
      .end(done);
```

这么跑的话，预期输出差的很远，只剩下一个 `\n` 了。

**Comment by popomore** [comment]
为啥，应该没啥区别，就是指定了路径，而不是通过 PATH 找

**Comment by afc163** [comment]
而且 code 是 1 。
